### ISSUE TITLE
Image Unknown Error

### ISSUE THREAD

**Issue by saglamhkn** [jobsta/reportbro-lib#10]
When I try to show image(url) from parameter in its ok in your demo's preview. But on my own server I am having this error. (except this issue my server is all ok). How can I fix this? Is this because of I use 2.7 version of python?

`2020-03-03 15:03:31,697: 500 PUT / (10.0.0.249) 77.99ms
2020-03-03 15:03:59,725: Uncaught exception PUT / (10.0.0.249)
HTTPServerRequest(protocol='https', host='saglamhkn.pythonanywhere.com', method='PUT', uri='/', version='HTTP/1.1', remote_ip='10.0.0.249')
Traceback (most recent call last):
  File "/home/saglamhkn/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/saglamhkn/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/saglamhkn/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/saglamhkn/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1221, in handle_yield
    self.future = convert_yielded(yielded)
  File "/home/saglamhkn/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/saglamhkn/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1363, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
BadYieldError: yielded unknown object '{"errors": []}'
2020-03-03 15:03:59,727: 500 PUT / (10.0.0.249) 23.09ms`

**Comment by alhman** [comment]
In the tornade example only ReportBroError is caught so you could also catch all Exceptions and log them to get more information about the error. The easiest way would be to run it locally and debug it.

In the latest version there is a setting _menuShowDebug_ for the designer. If you set it to true then there is a menu button where you can output the whole report definition to the javascript console. Copy the whole report definition and upload it somewhere (e.g. pastebin). Then I can have a look at this.
