### ISSUE TITLE
Tornado

### ISSUE THREAD

**Issue by lachlanhickey** [jobsta/reportbro-lib#2]
Issue when attempting to generate a report
`ServerRequest(protocol='http', host='XXX.XXX.XXX.XXX:8000', method='PUT', uri='/reportbro/report/run', version='HTTP/1.1', remote_ip='XXX.XXX.XXX.XXX')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1221, in handle_yield
    self.future = convert_yielded(yielded)
  File "/usr/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1363, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
tornado.gen.BadYieldError: yielded unknown object '{"errors": []}'
ERROR:tornado.access:500 PUT /reportbro/report/run (101.182.96.139) 432.37ms`

**Comment by alhman** [comment]
you should format your message correctly (hard to read) and also show how you initialize the web server.
